### ISSUE TITLE
0.2.0 release

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/Tokamak#131]
Just kickstarting a possible discussion here of what you'd like to see in the first release with the SwiftUI API subset supporting WebAssembly. I am personally a fan of "release early and often" idea and wouldn't mind tagging a release with whatever API coverage we already have. It's more about letting people know that this thing exists and it can do basic stuff.

These seem to be release blockers, let me know if you think anything's missing:

- [x] Basic documentation
       The existing `progress.md` should be enough for this first release, I guess? We can integrate [TokamakDocs](https://github.com/carson-katri/TokamakDocs/) somehow in later versions, unless @carson-katri has any objections.
- [ ] Cleaning up the demo example
       I think even without `NavigationView` and friends, I'll just add some padding and headers to describe what's what
- [x] Updated CHANGELOG.md
- [x] Tagging and sharing on Twitter

What are your thoughts @carson-katri @j-f1?

**Comment by MaxDesiatov** [comment]
One more thing, if you know of a suitable logo, or know anyone who could produce one, or can propose one yourself, please do. I've used stock images for the previous release with the React API, you can see them on [the Twitter profile](https://twitter.com/TokamakUI). If you're not familar with tokamaks, please use [the Wikipedia page](https://en.wikipedia.org/wiki/Tokamak) for inspirations. The whole idea was to make a pun on React's atomic logo 😄

**Comment by j-f1** [comment]
I tried to do something with Blender but it just looked bad. My idea was to make the plasma donut in the middle be Swift orange and have some sort of containment device around it in blue that still lets you see the orange.

**Comment by MaxDesiatov** [comment]
That sounds very cool 👍 I've created #132 specifically for the logo

**Comment by carson-katri** [comment]
I'm working on getting TokamakDocs to be more stable, but it could be run on a merge if possible...

**Comment by MaxDesiatov** [comment]
Great idea! I can host it on S3/CloudFront, just need to set up the deployment for it.

**Comment by carson-katri** [comment]
The most recent commit should be working with the `doc-gen` branch.

**Comment by carson-katri** [comment]
Should it be `1.0.0` (per [Semantic Versioning](https://semver.org/))?

**Comment by MaxDesiatov** [comment]
I'd prefer to bump it to `1.0.0` when reach close to 100% API coverage, otherwise we fall under this rule:

>Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by MaxDesiatov** [comment]
Especially if we tag the release before the Xcode 12 GM is out (which I hope we do), some of the new APIs could change by then. Using 0.y.z is safe from that perspective 😄

**Comment by MaxDesiatov** [comment]
0.2.0 is released, congratulations to everyone involved 👏

We kind of had a circular dependency where new features required a new release of `carton`, while a new release of `carton` required some new Tokamak release so that `carton init` can pull it in its new project template. The demo project is still not very organized, but let's resolve that separately as a part of https://github.com/swiftwasm/Tokamak/pull/130.

I think new releases will follow at much higher frequency now that we're fully out of hiatus 😄
